---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: pigeonos
description: Custom Bazzite-based bootc image
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: stable

modules:
  - type: dnf
    repos:
      cleanup: true
      copr:
        - scottames/ghostty
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - ghostty
        - zed
        - zsh

  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: true

  - type: os-release
    properties:
      ID: pigeonos
      NAME: "PigeonOS"
      PRETTY_NAME: "PigeonOS"

  - type: signing
